### ISSUE TITLE
Get finetuned model

### ISSUE THREAD

**Issue by jaytimbadia** [idanmoradarthas/Quora-Qusetions-Pairs-App#2]
Hi, This is not an issue, but more of a request.

I am currently working on sentence similarity classification. If possible, can you please provide your fine-tune model location for me to predict?

Also, I tried a few kinds of stuff using pre-trained models, but I am getting fixed prediction results.

Thank you!!

**Comment by idanmoradarthas** [comment]
The model is too big to upload to github.
you can recreate by yourself using the notebook in the train-bert directory
